version: '3.1'

services:
    minio:
        image: robertomendonca/ph-minio:1.2
        container_name: minio
        restart: always
        ports:
            - "4321:9000"
        volumes:
            - minio:/data
        command: server data

volumes:
    minio: